/*
 * Copyright 2019-2024 indunet.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.indunet.fastproto.formula;

import java.lang.reflect.Field;
import java.util.function.Function;

/**
 * Registry for looking up pre-compiled formula classes generated by the annotation processor.
 *
 * <p>This class attempts to locate the generated {@code FormulaRegistry} class at runtime
 * and delegates formula lookups to it. If no generated registry is found (e.g., when the
 * annotation processor was not used), lookups will return null.
 *
 * <p>The registry key format is: {@code "fullyQualifiedClassName#fieldName#formulaType"}
 * where formulaType is either "decoding" or "encoding".
 *
 * @author Deng Ran
 * @since 3.13.0
 */
public final class FormulaRegistry {

    private static final String GENERATED_REGISTRY_CLASS = "org.indunet.fastproto.formula.generated.FormulaRegistry";
    
    private static volatile Class<?> generatedRegistryClass;
    private static volatile boolean initialized = false;

    private FormulaRegistry() {
        // Utility class
    }

    /**
     * Initialize the registry by attempting to load the generated FormulaRegistry class.
     */
    private static synchronized void initialize() {
        if (initialized) {
            return;
        }
        try {
            generatedRegistryClass = Class.forName(GENERATED_REGISTRY_CLASS);
        } catch (ClassNotFoundException e) {
            // Generated registry not found - this is expected when annotation processor wasn't used
            generatedRegistryClass = null;
        }
        initialized = true;
    }

    /**
     * Build a registry key for a field's formula.
     *
     * @param declaringClass the class declaring the field
     * @param fieldName the field name
     * @param formulaType "decoding" or "encoding"
     * @return the registry key
     */
    public static String buildKey(Class<?> declaringClass, String fieldName, String formulaType) {
        return declaringClass.getName() + "#" + fieldName + "#" + formulaType;
    }

    /**
     * Build a registry key for a field's formula.
     *
     * @param field the field
     * @param formulaType "decoding" or "encoding"
     * @return the registry key
     */
    public static String buildKey(Field field, String formulaType) {
        return field.getDeclaringClass().getName() + "#" + field.getName() + "#" + formulaType;
    }

    /**
     * Get a pre-compiled formula by its registry key.
     *
     * @param key the registry key in format "className#fieldName#formulaType"
     * @param <T> the input type
     * @param <R> the return type
     * @return the formula function, or null if not found
     */
    @SuppressWarnings("unchecked")
    public static <T, R> Function<T, R> get(String key) {
        if (!initialized) {
            initialize();
        }
        
        if (generatedRegistryClass == null) {
            return null;
        }
        
        try {
            java.lang.reflect.Method getMethod = generatedRegistryClass.getMethod("get", String.class);
            return (Function<T, R>) getMethod.invoke(null, key);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Get a pre-compiled formula for a field.
     *
     * @param declaringClass the class declaring the field
     * @param fieldName the field name
     * @param formulaType "decoding" or "encoding"
     * @param <T> the input type
     * @param <R> the return type
     * @return the formula function, or null if not found
     */
    public static <T, R> Function<T, R> get(Class<?> declaringClass, String fieldName, String formulaType) {
        return get(buildKey(declaringClass, fieldName, formulaType));
    }

    /**
     * Get a pre-compiled formula for a field.
     *
     * @param field the field
     * @param formulaType "decoding" or "encoding"
     * @param <T> the input type
     * @param <R> the return type
     * @return the formula function, or null if not found
     */
    public static <T, R> Function<T, R> get(Field field, String formulaType) {
        return get(buildKey(field, formulaType));
    }

    /**
     * Check if a formula exists in the registry.
     *
     * @param key the registry key
     * @return true if the formula exists
     */
    public static boolean contains(String key) {
        if (!initialized) {
            initialize();
        }
        
        if (generatedRegistryClass == null) {
            return false;
        }
        
        try {
            java.lang.reflect.Method containsMethod = generatedRegistryClass.getMethod("contains", String.class);
            return (Boolean) containsMethod.invoke(null, key);
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Check if a formula exists for a field.
     *
     * @param field the field
     * @param formulaType "decoding" or "encoding"
     * @return true if the formula exists
     */
    public static boolean contains(Field field, String formulaType) {
        return contains(buildKey(field, formulaType));
    }

    /**
     * Check if the generated formula registry is available.
     *
     * @return true if the generated registry was found and loaded
     */
    public static boolean isAvailable() {
        if (!initialized) {
            initialize();
        }
        return generatedRegistryClass != null;
    }
}
