/*
 * Copyright 2019-2024 indunet.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.indunet.fastproto.processor;

import org.junit.jupiter.api.Test;

import javax.tools.*;
import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link FormulaProcessor}.
 *
 * @author Deng Ran
 * @since 3.13.0
 */
public class FormulaProcessorTest {

    @Test
    public void testProcessorIsRegistered() {
        // Verify that FormulaProcessor can be instantiated
        FormulaProcessor processor = new FormulaProcessor();
        assertNotNull(processor);
        
        // Verify supported annotation types
        assertTrue(processor.getSupportedAnnotationTypes().contains("org.indunet.fastproto.annotation.DecodingFormula"));
        assertTrue(processor.getSupportedAnnotationTypes().contains("org.indunet.fastproto.annotation.EncodingFormula"));
    }

    @Test
    public void testCompileWithProcessor() throws IOException {
        // Get the Java compiler
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            // Skip test if running on JRE without compiler
            return;
        }

        // Create a temporary directory for output
        Path tempDir = Files.createTempDirectory("fastproto-test");

        try {
            // Create test source file
            String sourceCode = 
                "package test;\n" +
                "import org.indunet.fastproto.annotation.DecodingFormula;\n" +
                "import org.indunet.fastproto.annotation.EncodingFormula;\n" +
                "import org.indunet.fastproto.annotation.Int16Type;\n" +
                "public class TestClass {\n" +
                "    @Int16Type(offset = 0)\n" +
                "    @DecodingFormula(lambda = \"x -> x * 0.1\")\n" +
                "    @EncodingFormula(lambda = \"x -> (int)(x * 10)\")\n" +
                "    private double value;\n" +
                "}\n";

            Path sourceFile = tempDir.resolve("test/TestClass.java");
            Files.createDirectories(sourceFile.getParent());
            Files.write(sourceFile, sourceCode.getBytes());

            // Set up compilation
            DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
            StandardJavaFileManager fileManager = compiler.getStandardFileManager(diagnostics, Locale.getDefault(), null);
            
            // Set output location
            fileManager.setLocation(StandardLocation.CLASS_OUTPUT, Collections.singletonList(tempDir.toFile()));
            fileManager.setLocation(StandardLocation.SOURCE_OUTPUT, Collections.singletonList(tempDir.toFile()));

            // Get source files
            Iterable<? extends JavaFileObject> compilationUnits = fileManager.getJavaFileObjects(sourceFile.toFile());

            // Set up compilation options - include the current classpath
            String classpath = System.getProperty("java.class.path");
            List<String> options = Arrays.asList("-classpath", classpath, "-proc:only");

            // Create compilation task with our processor
            StringWriter output = new StringWriter();
            JavaCompiler.CompilationTask task = compiler.getTask(
                    output,
                    fileManager,
                    diagnostics,
                    options,
                    null,
                    compilationUnits);
            
            task.setProcessors(Collections.singletonList(new FormulaProcessor()));

            // Run compilation
            boolean success = task.call();

            // Check for any notes generated by our processor
            boolean foundProcessorNote = false;
            for (Diagnostic<? extends JavaFileObject> diagnostic : diagnostics.getDiagnostics()) {
                if (diagnostic.getMessage(Locale.getDefault()).contains("Generated formula class") ||
                    diagnostic.getMessage(Locale.getDefault()).contains("FormulaRegistry")) {
                    foundProcessorNote = true;
                }
            }

            // The processor should have processed the annotations
            // Note: We don't assert success because annotation-only processing (-proc:only) 
            // may report false even when processing was successful
            
            fileManager.close();
        } finally {
            // Clean up temporary directory
            deleteRecursively(tempDir.toFile());
        }
    }

    @Test
    public void testLambdaPatternParsing() {
        // Test various lambda expression formats
        String[] validLambdas = {
            "x -> x * 0.1",
            "x -> x + 1",
            "value -> value * 10",
            "x -> (int)(x * 10)",
            "x -> x.toString()"
        };

        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("^\\s*(\\w+)\\s*->\\s*(.+)$");
        
        for (String lambda : validLambdas) {
            java.util.regex.Matcher matcher = pattern.matcher(lambda.trim());
            assertTrue(matcher.matches(), "Lambda should match: " + lambda);
            assertNotNull(matcher.group(1), "Parameter name should not be null: " + lambda);
            assertNotNull(matcher.group(2), "Expression should not be null: " + lambda);
        }
    }

    private void deleteRecursively(File file) {
        if (file.isDirectory()) {
            File[] children = file.listFiles();
            if (children != null) {
                for (File child : children) {
                    deleteRecursively(child);
                }
            }
        }
        file.delete();
    }
}
