package org.indunet.fastproto.ros2;

import org.indunet.fastproto.ros2.builtin_interfaces.msg.Duration;
import org.indunet.fastproto.ros2.builtin_interfaces.msg.Time;
import org.indunet.fastproto.ros2.codecs.BuiltinRos2Codecs;
import org.indunet.fastproto.ros2.codecs.GeometryRos2Codecs;
import org.indunet.fastproto.ros2.codecs.NavRos2Codecs;
import org.indunet.fastproto.ros2.codecs.SensorRos2Codecs;
import org.indunet.fastproto.ros2.codecs.StdRos2Codecs;
import org.indunet.fastproto.ros2.codecs.Tf2Ros2Codecs;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Accel;
import org.indunet.fastproto.ros2.geometry_msgs.msg.AccelWithCovariance;
import org.indunet.fastproto.ros2.geometry_msgs.msg.AccelWithCovarianceStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.AccelStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Inertia;
import org.indunet.fastproto.ros2.geometry_msgs.msg.InertiaStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Point;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Point32;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PointStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Pose;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Pose2D;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PoseArray;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PoseStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PoseWithCovariance;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PoseWithCovarianceStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Polygon;
import org.indunet.fastproto.ros2.geometry_msgs.msg.PolygonStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Quaternion;
import org.indunet.fastproto.ros2.geometry_msgs.msg.QuaternionStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Transform;
import org.indunet.fastproto.ros2.geometry_msgs.msg.TransformStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Twist;
import org.indunet.fastproto.ros2.geometry_msgs.msg.TwistStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.TwistWithCovariance;
import org.indunet.fastproto.ros2.geometry_msgs.msg.TwistWithCovarianceStamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Vector3;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Vector3Stamped;
import org.indunet.fastproto.ros2.geometry_msgs.msg.Wrench;
import org.indunet.fastproto.ros2.geometry_msgs.msg.WrenchStamped;
import org.indunet.fastproto.ros2.nav_msgs.msg.MapMetaData;
import org.indunet.fastproto.ros2.nav_msgs.msg.GridCells;
import org.indunet.fastproto.ros2.nav_msgs.msg.Odometry;
import org.indunet.fastproto.ros2.nav_msgs.msg.OccupancyGrid;
import org.indunet.fastproto.ros2.nav_msgs.msg.Path;
import org.indunet.fastproto.ros2.sensor_msgs.msg.BatteryState;
import org.indunet.fastproto.ros2.sensor_msgs.msg.CameraInfo;
import org.indunet.fastproto.ros2.sensor_msgs.msg.ChannelFloat32;
import org.indunet.fastproto.ros2.sensor_msgs.msg.CompressedImage;
import org.indunet.fastproto.ros2.sensor_msgs.msg.FluidPressure;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Image;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Illuminance;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Imu;
import org.indunet.fastproto.ros2.sensor_msgs.msg.JointState;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Joy;
import org.indunet.fastproto.ros2.sensor_msgs.msg.JoyFeedback;
import org.indunet.fastproto.ros2.sensor_msgs.msg.JoyFeedbackArray;
import org.indunet.fastproto.ros2.sensor_msgs.msg.LaserEcho;
import org.indunet.fastproto.ros2.sensor_msgs.msg.LaserScan;
import org.indunet.fastproto.ros2.sensor_msgs.msg.MagneticField;
import org.indunet.fastproto.ros2.sensor_msgs.msg.MultiEchoLaserScan;
import org.indunet.fastproto.ros2.sensor_msgs.msg.NavSatFix;
import org.indunet.fastproto.ros2.sensor_msgs.msg.NavSatStatus;
import org.indunet.fastproto.ros2.sensor_msgs.msg.PointCloud;
import org.indunet.fastproto.ros2.sensor_msgs.msg.PointCloud2;
import org.indunet.fastproto.ros2.sensor_msgs.msg.PointField;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Range;
import org.indunet.fastproto.ros2.sensor_msgs.msg.RegionOfInterest;
import org.indunet.fastproto.ros2.sensor_msgs.msg.RelativeHumidity;
import org.indunet.fastproto.ros2.sensor_msgs.msg.Temperature;
import org.indunet.fastproto.ros2.sensor_msgs.msg.TimeReference;
import org.indunet.fastproto.ros2.std_msgs.msg.Bool;
import org.indunet.fastproto.ros2.std_msgs.msg.Byte;
import org.indunet.fastproto.ros2.std_msgs.msg.Char;
import org.indunet.fastproto.ros2.std_msgs.msg.ColorRGBA;
import org.indunet.fastproto.ros2.std_msgs.msg.Empty;
import org.indunet.fastproto.ros2.std_msgs.msg.Float32;
import org.indunet.fastproto.ros2.std_msgs.msg.Float32MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.Float64;
import org.indunet.fastproto.ros2.std_msgs.msg.Float64MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.Header;
import org.indunet.fastproto.ros2.std_msgs.msg.Int8;
import org.indunet.fastproto.ros2.std_msgs.msg.Int8MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.Int16;
import org.indunet.fastproto.ros2.std_msgs.msg.Int16MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.Int64;
import org.indunet.fastproto.ros2.std_msgs.msg.Int64MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.Int32;
import org.indunet.fastproto.ros2.std_msgs.msg.Int32MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.MultiArrayDimension;
import org.indunet.fastproto.ros2.std_msgs.msg.MultiArrayLayout;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt16;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt16MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt32;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt32MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt64;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt64MultiArray;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt8;
import org.indunet.fastproto.ros2.std_msgs.msg.UInt8MultiArray;
import org.indunet.fastproto.ros2.tf2_msgs.msg.TFMessage;

/**
 * Public facade for the built-in ROS2 codecs.
 */
public final class Ros2Codecs {
    public static final Ros2Codec<Time> TIME = BuiltinRos2Codecs.TIME;
    public static final Ros2Codec<Duration> DURATION = BuiltinRos2Codecs.DURATION;

    public static final Ros2Codec<Point> POINT = GeometryRos2Codecs.POINT;
    public static final Ros2Codec<Point32> POINT32 = GeometryRos2Codecs.POINT32;
    public static final Ros2Codec<Pose2D> POSE2D = GeometryRos2Codecs.POSE2D;
    public static final Ros2Codec<Quaternion> QUATERNION = GeometryRos2Codecs.QUATERNION;
    public static final Ros2Codec<Vector3> VECTOR3 = GeometryRos2Codecs.VECTOR3;
    public static final Ros2Codec<Pose> POSE = GeometryRos2Codecs.POSE;
    public static final Ros2Codec<Polygon> POLYGON = GeometryRos2Codecs.POLYGON;
    public static final Ros2Codec<PointStamped> POINT_STAMPED = GeometryRos2Codecs.POINT_STAMPED;
    public static final Ros2Codec<Vector3Stamped> VECTOR3_STAMPED = GeometryRos2Codecs.VECTOR3_STAMPED;
    public static final Ros2Codec<QuaternionStamped> QUATERNION_STAMPED = GeometryRos2Codecs.QUATERNION_STAMPED;
    public static final Ros2Codec<Twist> TWIST = GeometryRos2Codecs.TWIST;
    public static final Ros2Codec<Transform> TRANSFORM = GeometryRos2Codecs.TRANSFORM;
    public static final Ros2Codec<Accel> ACCEL = GeometryRos2Codecs.ACCEL;
    public static final Ros2Codec<AccelWithCovariance> ACCEL_WITH_COVARIANCE = GeometryRos2Codecs.ACCEL_WITH_COVARIANCE;
    public static final Ros2Codec<Wrench> WRENCH = GeometryRos2Codecs.WRENCH;
    public static final Ros2Codec<Inertia> INERTIA = GeometryRos2Codecs.INERTIA;
    public static final Ros2Codec<PoseStamped> POSE_STAMPED = GeometryRos2Codecs.POSE_STAMPED;
    public static final Ros2Codec<PolygonStamped> POLYGON_STAMPED = GeometryRos2Codecs.POLYGON_STAMPED;
    public static final Ros2Codec<AccelStamped> ACCEL_STAMPED = GeometryRos2Codecs.ACCEL_STAMPED;
    public static final Ros2Codec<AccelWithCovarianceStamped> ACCEL_WITH_COVARIANCE_STAMPED =
            GeometryRos2Codecs.ACCEL_WITH_COVARIANCE_STAMPED;
    public static final Ros2Codec<TwistStamped> TWIST_STAMPED = GeometryRos2Codecs.TWIST_STAMPED;
    public static final Ros2Codec<TwistWithCovarianceStamped> TWIST_WITH_COVARIANCE_STAMPED =
            GeometryRos2Codecs.TWIST_WITH_COVARIANCE_STAMPED;
    public static final Ros2Codec<WrenchStamped> WRENCH_STAMPED = GeometryRos2Codecs.WRENCH_STAMPED;
    public static final Ros2Codec<InertiaStamped> INERTIA_STAMPED = GeometryRos2Codecs.INERTIA_STAMPED;
    public static final Ros2Codec<TransformStamped> TRANSFORM_STAMPED = GeometryRos2Codecs.TRANSFORM_STAMPED;
    public static final Ros2Codec<PoseWithCovariance> POSE_WITH_COVARIANCE = GeometryRos2Codecs.POSE_WITH_COVARIANCE;
    public static final Ros2Codec<PoseWithCovarianceStamped> POSE_WITH_COVARIANCE_STAMPED =
            GeometryRos2Codecs.POSE_WITH_COVARIANCE_STAMPED;
    public static final Ros2Codec<PoseArray> POSE_ARRAY = GeometryRos2Codecs.POSE_ARRAY;
    public static final Ros2Codec<TwistWithCovariance> TWIST_WITH_COVARIANCE =
            GeometryRos2Codecs.TWIST_WITH_COVARIANCE;

    public static final Ros2Codec<Header> HEADER = StdRos2Codecs.HEADER;
    public static final Ros2Codec<Empty> EMPTY = StdRos2Codecs.EMPTY;
    public static final Ros2Codec<Bool> BOOL = StdRos2Codecs.BOOL;
    public static final Ros2Codec<Byte> BYTE = StdRos2Codecs.BYTE;
    public static final Ros2Codec<Char> CHAR = StdRos2Codecs.CHAR;
    public static final Ros2Codec<Int8> INT8 = StdRos2Codecs.INT8;
    public static final Ros2Codec<Int16> INT16 = StdRos2Codecs.INT16;
    public static final Ros2Codec<Int32> INT32 = StdRos2Codecs.INT32;
    public static final Ros2Codec<Int64> INT64 = StdRos2Codecs.INT64;
    public static final Ros2Codec<UInt16> UINT16 = StdRos2Codecs.UINT16;
    public static final Ros2Codec<UInt32> UINT32 = StdRos2Codecs.UINT32;
    public static final Ros2Codec<UInt64> UINT64 = StdRos2Codecs.UINT64;
    public static final Ros2Codec<UInt8> UINT8 = StdRos2Codecs.UINT8;
    public static final Ros2Codec<Float32> FLOAT32 = StdRos2Codecs.FLOAT32;
    public static final Ros2Codec<Float64> FLOAT64 = StdRos2Codecs.FLOAT64;
    public static final Ros2Codec<org.indunet.fastproto.ros2.std_msgs.msg.String> STD_STRING = StdRos2Codecs.STD_STRING;
    public static final Ros2Codec<ColorRGBA> COLOR_RGBA = StdRos2Codecs.COLOR_RGBA;
    public static final Ros2Codec<MultiArrayDimension> MULTI_ARRAY_DIMENSION = StdRos2Codecs.MULTI_ARRAY_DIMENSION;
    public static final Ros2Codec<MultiArrayLayout> MULTI_ARRAY_LAYOUT = StdRos2Codecs.MULTI_ARRAY_LAYOUT;
    public static final Ros2Codec<Float32MultiArray> FLOAT32_MULTI_ARRAY = StdRos2Codecs.FLOAT32_MULTI_ARRAY;
    public static final Ros2Codec<Float64MultiArray> FLOAT64_MULTI_ARRAY = StdRos2Codecs.FLOAT64_MULTI_ARRAY;
    public static final Ros2Codec<Int8MultiArray> INT8_MULTI_ARRAY = StdRos2Codecs.INT8_MULTI_ARRAY;
    public static final Ros2Codec<Int32MultiArray> INT32_MULTI_ARRAY = StdRos2Codecs.INT32_MULTI_ARRAY;
    public static final Ros2Codec<Int16MultiArray> INT16_MULTI_ARRAY = StdRos2Codecs.INT16_MULTI_ARRAY;
    public static final Ros2Codec<Int64MultiArray> INT64_MULTI_ARRAY = StdRos2Codecs.INT64_MULTI_ARRAY;
    public static final Ros2Codec<UInt16MultiArray> UINT16_MULTI_ARRAY = StdRos2Codecs.UINT16_MULTI_ARRAY;
    public static final Ros2Codec<UInt32MultiArray> UINT32_MULTI_ARRAY = StdRos2Codecs.UINT32_MULTI_ARRAY;
    public static final Ros2Codec<UInt64MultiArray> UINT64_MULTI_ARRAY = StdRos2Codecs.UINT64_MULTI_ARRAY;
    public static final Ros2Codec<UInt8MultiArray> UINT8_MULTI_ARRAY = StdRos2Codecs.UINT8_MULTI_ARRAY;

    public static final Ros2Codec<Imu> IMU = SensorRos2Codecs.IMU;
    public static final Ros2Codec<Image> IMAGE = SensorRos2Codecs.IMAGE;
    public static final Ros2Codec<CompressedImage> COMPRESSED_IMAGE = SensorRos2Codecs.COMPRESSED_IMAGE;
    public static final Ros2Codec<ChannelFloat32> CHANNEL_FLOAT32 = SensorRos2Codecs.CHANNEL_FLOAT32;
    public static final Ros2Codec<LaserEcho> LASER_ECHO = SensorRos2Codecs.LASER_ECHO;
    public static final Ros2Codec<RegionOfInterest> REGION_OF_INTEREST = SensorRos2Codecs.REGION_OF_INTEREST;
    public static final Ros2Codec<PointField> POINT_FIELD = SensorRos2Codecs.POINT_FIELD;
    public static final Ros2Codec<NavSatStatus> NAV_SAT_STATUS = SensorRos2Codecs.NAV_SAT_STATUS;
    public static final Ros2Codec<CameraInfo> CAMERA_INFO = SensorRos2Codecs.CAMERA_INFO;
    public static final Ros2Codec<MagneticField> MAGNETIC_FIELD = SensorRos2Codecs.MAGNETIC_FIELD;
    public static final Ros2Codec<Temperature> TEMPERATURE = SensorRos2Codecs.TEMPERATURE;
    public static final Ros2Codec<FluidPressure> FLUID_PRESSURE = SensorRos2Codecs.FLUID_PRESSURE;
    public static final Ros2Codec<Illuminance> ILLUMINANCE = SensorRos2Codecs.ILLUMINANCE;
    public static final Ros2Codec<RelativeHumidity> RELATIVE_HUMIDITY = SensorRos2Codecs.RELATIVE_HUMIDITY;
    public static final Ros2Codec<PointCloud2> POINT_CLOUD2 = SensorRos2Codecs.POINT_CLOUD2;
    public static final Ros2Codec<PointCloud> POINT_CLOUD = SensorRos2Codecs.POINT_CLOUD;
    public static final Ros2Codec<LaserScan> LASER_SCAN = SensorRos2Codecs.LASER_SCAN;
    public static final Ros2Codec<MultiEchoLaserScan> MULTI_ECHO_LASER_SCAN = SensorRos2Codecs.MULTI_ECHO_LASER_SCAN;
    public static final Ros2Codec<Range> RANGE = SensorRos2Codecs.RANGE;
    public static final Ros2Codec<NavSatFix> NAV_SAT_FIX = SensorRos2Codecs.NAV_SAT_FIX;
    public static final Ros2Codec<Joy> JOY = SensorRos2Codecs.JOY;
    public static final Ros2Codec<JoyFeedback> JOY_FEEDBACK = SensorRos2Codecs.JOY_FEEDBACK;
    public static final Ros2Codec<JoyFeedbackArray> JOY_FEEDBACK_ARRAY = SensorRos2Codecs.JOY_FEEDBACK_ARRAY;
    public static final Ros2Codec<JointState> JOINT_STATE = SensorRos2Codecs.JOINT_STATE;
    public static final Ros2Codec<BatteryState> BATTERY_STATE = SensorRos2Codecs.BATTERY_STATE;
    public static final Ros2Codec<TimeReference> TIME_REFERENCE = SensorRos2Codecs.TIME_REFERENCE;

    public static final Ros2Codec<MapMetaData> MAP_META_DATA = NavRos2Codecs.MAP_META_DATA;
    public static final Ros2Codec<GridCells> GRID_CELLS = NavRos2Codecs.GRID_CELLS;
    public static final Ros2Codec<OccupancyGrid> OCCUPANCY_GRID = NavRos2Codecs.OCCUPANCY_GRID;
    public static final Ros2Codec<Odometry> ODOMETRY = NavRos2Codecs.ODOMETRY;
    public static final Ros2Codec<Path> PATH = NavRos2Codecs.PATH;

    public static final Ros2Codec<TFMessage> TF_MESSAGE = Tf2Ros2Codecs.TF_MESSAGE;

    private Ros2Codecs() {
    }
}
